#!/bin/bash
lastBlockNumber="$(./lastBlockNumber)"
blockNumber="$(./blockNumber)"
printf \
  'export default [[{name: "web3subgraph",extractor: {args: ["%s", "%s"]},transformer: {},},],];' \
  $lastBlockNumber $blockNumber

